### ISSUE TITLE
Add automated validation check for API

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorhub-topic-api#1]
One way this could be done is through github actions. A way of doing this via the swagger editor is described in a blog post: https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/

Accordingly, it would look something like this

```yaml
on: [push]


jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote


    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: docs/openapi.yaml
```

Perhaps a badge could also be added to the repository's README.md to show that it has been validated as well.
